.gitignore, apiary-metastore-listener/pom.xml, apiary-metastore-listener/src/main/java/com/expedia/apiary/extensions/metastore/listener/ApiarySnsListener.java, apiary-metastore-listener/src/test/java/com/expedia/apiary/extensions/metastore/listener/ApiarySnsListenerTest.java, apiary-metastore-listener/src/test/resources/log4j2.xml, pom.xml
I've tried to move the code from https://github.com/ExpediaInc/apiary-metastore-docker/blob/master/src/ApiarySNSListener.java over here more or less as is but needed to make some breaking changes like putting the class in the correct package. Since this is a breaking change we might as well do whatever else we think is necessary to this class now so I also removed the system.outs and replaced them with slf4j. I'm sure we'll find plenty of other things we want/need to change before we can get this released to Maven Central but hopefully they can be handled in other PRs and this should be viewed as just getting a "base" version out there.
=> Initial project skeleton and metastore listener

apiary-metastore-metrics/README.md, apiary-metastore-metrics/pom.xml, apiary-metastore-metrics/src/main/java/com/expedia/apiary/extensions/metastore/metrics/CloudwatchReporter.java, apiary-metastore-metrics/src/main/java/com/expedia/apiary/extensions/metastore/metrics/CodahaleMetrics.java, apiary-metastore-metrics/src/test/java/com/expedia/apiary/extensions/metastore/metrics/CodahaleMetricsTest.java, apiary-metastore-metrics/src/test/java/com/expedia/apiary/extensions/metastore/metrics/MetricsTestUtils.java, apiary-metastore-metrics/src/test/java/com/expedia/apiary/extensions/metastore/metrics/TestCodahaleMetrics.java, pom.xml
This is mostly based on following, just added CloudwatchReporter nested class
https://github.com/apache/hive/blob/branch-2.3/common/src/java/org/apache/hadoop/hive/common/metrics/metrics2/CodahaleMetrics.java
https://github.com/apache/hive/blob/branch-2.3/common/src/test/org/apache/hadoop/hive/common/metrics/metrics2/TestCodahaleMetrics.java
Note: hive 3.0.0 natively supports custom classes for reporters, so this will be simpler when we move to hive 3.0.0
https://cwiki.apache.org/confluence/display/Hive/Configuration+Properties#ConfigurationProperties-Metrics
=> fixes #12 cloudwatch metastore metrics reporter

CHANGELOG.md, apiary-gluesync-listener/pom.xml, apiary-metastore-listener/README.md, apiary-metastore-listener/pom.xml, apiary-metastore-listener/src/main/java/com/expedia/apiary/extensions/metastore/listener/ApiarySnsListener.java, apiary-metastore-listener/src/test/java/com/expedia/apiary/extensions/metastore/listener/ApiarySnsListenerTest.java, apiary-metastore-metrics/pom.xml, apiary-ranger-metastore-plugin/pom.xml, pom.xml
The JSON Response from the Listener marshals the Array as a String which is not ideal and requires unnecessary processing on the receiver side.
=> Fixing JSON Response from Apiary Hive Metastore Listener

CHANGELOG.md, apiary-receivers/apiary-receiver-sqs/pom.xml
Removing dependency of entire AWS java sdk from `apiary-receiver-sqs`.
=> Remove dependency

CHANGELOG.md, apiary-gluesync-listener/pom.xml, apiary-metastore-auth/pom.xml, apiary-metastore-listener/pom.xml, apiary-metastore-metrics/pom.xml, apiary-ranger-metastore-plugin/pom.xml, apiary-receivers/apiary-receiver-common/pom.xml, apiary-receivers/apiary-receiver-sqs/pom.xml, apiary-receivers/pom.xml, pom.xml
I need to change the Maven Group ID in order for the CICD pipeline to be able to produce artifacts as it is now using a user which has push access to `com.expediagroup` not `com.expedia`.
I plan to do this in two stages. The first stage (in this PR) just changes the group ID in the pom.xml files but leaves the Java code packaged in the `com.expedia.apiary` package. Once I can publish SNAPSHOTs using the CICD pipeline with this new group ID then I will raise another PR which repackages all the Java code so that the base package matches the groupId. 
These two changes will be bundled into a 3.0.0 version of apiary-extensions. Once that's released I'll change all the downstream projects to pull in this version and update any references to Java classnames.
=> changed Maven group ID to `com.expediagroup.apiary`

CHANGELOG.md, apiary-metastore-listener/src/main/java/com/expediagroup/apiary/extensions/metastore/listener/ApiarySnsListener.java, apiary-metastore-listener/src/test/java/com/expediagroup/apiary/extensions/metastore/listener/ApiarySnsListenerTest.java
The table parameters on a Hive Metastore event should be serialised as a Map, but are currently serialised as a String.
Current:
```
... ,\"tableParameters\":\"{MY_VAR_TWO=5, MY_VAR_ONE=true}\", ...
```
Fix:
```
... ,\"tableParameters\":{\"MY_VAR_TWO\":\"5\",\"MY_VAR_ONE\":\"true\"}, ...
```
=> Fix for apiary-metastore-listener table parameters

CHANGELOG.md, apiary-gluesync-listener/pom.xml, apiary-metastore-auth/pom.xml, apiary-metastore-events/apiary-metastore-consumers/metastore-consumer-common/pom.xml, apiary-metastore-events/apiary-metastore-consumers/pom.xml, apiary-metastore-events/apiary-metastore-consumers/privileges-grantor/pom.xml, apiary-metastore-events/apiary-metastore-consumers/privileges-grantor/privileges-grantor-core/pom.xml, apiary-metastore-events/apiary-metastore-consumers/privileges-grantor/privileges-grantor-lambda/pom.xml, apiary-metastore-events/apiary-metastore-listener/pom.xml, apiary-metastore-events/apiary-receivers/apiary-receiver-common/pom.xml, apiary-metastore-events/apiary-receivers/apiary-receiver-sqs/pom.xml, apiary-metastore-events/apiary-receivers/pom.xml, apiary-metastore-events/pom.xml, apiary-metastore-metrics/pom.xml, apiary-ranger-metastore-plugin/pom.xml, apiary-ranger-metastore-plugin/src/main/java/com/expediagroup/apiary/extensions/rangerauth/listener/ApiaryRangerAuthPreEventListener.java, apiary-ranger-metastore-plugin/src/main/java/com/expediagroup/apiary/extensions/rangerauth/policyproviders/ApiaryRangerAuthAllAccessPolicyProvider.java, apiary-ranger-metastore-plugin/src/test/java/com/expediagroup/apiary/extensions/rangerauth/policyproviders/ApiaryRangerAuthAllAccessPolicyProviderTest.java, pom.xml
This PR creates a new class `ApiaryRangerAuthAllAccessPolicyProvider` that implements the interface that Ranger HMS plugin uses to load authorization policies.  This class returns a single policy that allows all access, since we are relying on other features of the HMS RO endpoint to filter out certain schemas, and to enforce read-only access.
This class will be set in the `ranger.plugin.hive.policy.source.impl` property of the `/etc/hive/conf/ranger-hive-security.xml` file by the `apiary-metastore-docker` project for the RO HMS instance.
=> Add support for Ranger audit-only mode on readonly HMS

hive-metastore-events/apiary-ranger-metastore-plugin/src/main/java/com/expediagroup/apiary/extensions/rangerauth/policyproviders/ApiaryRangerAuthAllAccessPolicyProvider.java, hive-metastore-events/apiary-ranger-metastore-plugin/src/test/java/com/expediagroup/apiary/extensions/rangerauth/listener/RangerAdminClientImpl.java, pom.xml
Update stub implementations of interface to have new methods that do nothing/return nothing, since they are only used in tests.
=> Upgrade ranger plugin to 2.0.0

CHANGELOG.md, pom.xml
- Changed parent to `com.expediagroup:eg-oss-parent:1.1.0` (was`com.hotels:hotels-oss-parent:4.0.1`).
- changed scm section to be https instead of ssh
=> Update parent and scm

CHANGELOG.md, hive-metastore-events/apiary-ranger-metastore-plugin/pom.xml, pom.xml
When `apiary-ranger-metastore-plugin` was upgraded to use Ranger `2.0.0`, the underlying Ranger 2.0.0 jars were built with a newer version of Solr that changed the classes uses to create the client.  However, this project was shading in the old version of Solr, causing a `ClassNotFoundException` whenever auditing via Solr was initializing.
This PR changes the shaded Solr version to the same version used by Apache to build Ranger `2.0.0`.
=> Upgrade solr jar version to match what Ranger 2.0.0 plugin expects

CHANGELOG.md, apiary-metastore-events/apiary-hive-events/src/test/java/com/expediagroup/apiary/extensions/events/metastore/io/jackson/JacksonThriftSerializerTest.java, apiary-metastore-events/kafka-metastore-events/kafka-metastore-listener/src/test/java/com/expediagroup/apiary/extensions/events/metastore/kafka/messaging/KafkaMessageSenderTest.java, apiary-metastore-events/kafka-metastore-events/kafka-metastore-listener/src/test/java/com/expediagroup/apiary/extensions/events/metastore/kafka/messaging/KafkaMessageTest.java, apiary-metastore-events/sns-metastore-events/apiary-metastore-consumers/metastore-consumer-common/src/main/java/com/expediagroup/apiary/extensions/events/metastore/consumer/common/thrift/ThriftHiveClient.java, hive-metastore-events/apiary-ranger-metastore-plugin/src/main/java/com/expediagroup/apiary/extensions/rangerauth/policyproviders/ApiaryRangerAuthAllAccessPolicyProvider.java, hive-metastore-events/apiary-ranger-metastore-plugin/src/test/java/com/expediagroup/apiary/extensions/rangerauth/policyproviders/ApiaryRangerAuthAllAccessPolicyProviderTest.java, pom.xml
Ensures consistent import ordering via the Spotless plugin included in this proposed change to the parent pom - https://github.com/ExpediaGroup/eg-oss-parent/pull/8/files
=> `eg-oss-parent` version updated to 1.2.0 (was 1.1.0).

CHANGELOG.md, apiary-metastore-events/sns-metastore-events/apiary-metastore-listener/README.md, apiary-metastore-events/sns-metastore-events/apiary-metastore-listener/src/main/java/com/expediagroup/apiary/extensions/events/metastore/listener/ApiarySnsListener.java, apiary-metastore-events/sns-metastore-events/apiary-metastore-listener/src/main/java/com/expediagroup/apiary/extensions/events/metastore/listener/MessageAttributeKey.java, apiary-metastore-events/sns-metastore-events/apiary-metastore-listener/src/test/java/com/expediagroup/apiary/extensions/events/metastore/listener/ApiarySnsListenerTest.java
Combined the db and table message attributes.
Being separate had the issue that a table with the same name in multiple dbs couldn't not easily subscribed to. Using qualified names it is more accurate.
=> adding qualified name as message attribute for filtering

CHANGELOG.md, apiary-metastore-events/apiary-hive-events/src/main/java/com/expediagroup/apiary/extensions/events/metastore/event/ApiaryListenerEventFactory.java, apiary-metastore-events/apiary-hive-events/src/test/java/com/expediagroup/apiary/extensions/events/metastore/io/jackson/JacksonThriftSerializerTest.java, apiary-metastore-events/sns-metastore-events/apiary-metastore-consumers/metastore-consumer-common/src/main/java/com/expediagroup/apiary/extensions/events/metastore/consumer/common/thrift/ThriftHiveClient.java, apiary-metastore-events/sns-metastore-events/apiary-metastore-consumers/privileges-grantor/privileges-grantor-lambda/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-metastore-consumers/privileges-grantor/privileges-grantor-lambda/src/main/java/com/expediagroup/apiary/extensions/events/metastore/consumer/privilegesgrantor/lambda/PrivilegesGrantorLambda.java, apiary-metastore-events/sns-metastore-events/apiary-metastore-consumers/privileges-grantor/privileges-grantor-lambda/src/test/java/com/expediagroup/apiary/extensions/events/metastore/consumer/privilegesgrantor/lambda/PrivilegesGrantorLambdaTest.java, apiary-metastore-events/sns-metastore-events/apiary-metastore-listener/src/main/java/com/expediagroup/apiary/extensions/events/metastore/listener/ApiarySnsListener.java, apiary-metastore-events/sns-metastore-events/apiary-metastore-listener/src/main/java/com/expediagroup/apiary/extensions/events/metastore/listener/MessageAttributeKey.java, apiary-metastore-events/sns-metastore-events/apiary-metastore-listener/src/test/java/com/expediagroup/apiary/extensions/events/metastore/listener/ApiarySnsListenerTest.java, apiary-metastore-events/sns-metastore-events/apiary-receivers/apiary-receiver-sqs/src/test/java/com/expediagroup/apiary/extensions/events/receiver/sqs/DefaultSqsMessageDeserializerTest.java, hive-metastore-events/apiary-ranger-metastore-plugin/src/main/java/com/expediagroup/apiary/extensions/rangerauth/policyproviders/ApiaryRangerAuthAllAccessPolicyProvider.java, hive-metastore-events/apiary-ranger-metastore-plugin/src/test/java/com/expediagroup/apiary/extensions/rangerauth/policyproviders/ApiaryRangerAuthAllAccessPolicyProviderTest.java
The right deserializer was not being used in the Privileges Grantor Lambda. This was causing deserialization exception when trying to use it.
=> fixing bug in privilege grantor lambda

CHANGELOG.md, pom.xml
* Upgraded version of `hive.version` to `2.3.7` (was `2.3.3`). Allows apiary-extensions to be used on JDK>=9.
=> Upgrade Hive to 2.3.7

.github/workflows/main.yml, CHANGELOG.md, apiary-metastore-events/apiary-hive-events/pom.xml, apiary-metastore-events/kafka-metastore-events/kafka-metastore-integration-tests/pom.xml, apiary-metastore-events/kafka-metastore-events/kafka-metastore-listener/pom.xml, apiary-metastore-events/kafka-metastore-events/kafka-metastore-receiver/pom.xml, apiary-metastore-events/kafka-metastore-events/pom.xml, apiary-metastore-events/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-metastore-consumers/metastore-consumer-common/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-metastore-consumers/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-metastore-consumers/privileges-grantor/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-metastore-consumers/privileges-grantor/privileges-grantor-core/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-metastore-consumers/privileges-grantor/privileges-grantor-lambda/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-metastore-listener/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-receivers/apiary-receiver-common/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-receivers/apiary-receiver-sqs/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-receivers/pom.xml, apiary-metastore-events/sns-metastore-events/pom.xml, apiary-metastore-metrics/pom.xml, hive-event-listeners/apiary-gluesync-listener/pom.xml, hive-event-listeners/apiary-metastore-auth/pom.xml, hive-event-listeners/apiary-ranger-metastore-plugin/pom.xml, hive-event-listeners/pom.xml, pom.xml
Update to `2.3.2` of `eg-oss-parent` to check that changes there for Javadoc issues with certain versions of Java don't affect a downstream build. Added a GH action build matrix of both Java 8 and 11 to demonstrate this.
=> Parent update

CHANGELOG.md, hive-event-listeners/apiary-gluesync-listener/pom.xml, hive-event-listeners/apiary-gluesync-listener/src/main/java/com/expediagroup/apiary/extensions/gluesync/listener/ApiaryGlueSync.java, hive-event-listeners/apiary-gluesync-listener/src/test/java/com/expediagroup/apiary/extensions/gluesync/listener/ApiaryGlueSyncTest.java, hive-event-listeners/apiary-gluesync-listener/src/test/java/com/expediagroup/apiary/extensions/gluesync/listener/IcebergTableOperations.java
=> Fix gluesync when getting null SortOrders in Hive & Iceberg tables

CHANGELOG.md, apiary-metastore-events/kafka-metastore-events/kafka-metastore-listener/src/main/java/com/expediagroup/apiary/extensions/events/metastore/kafka/messaging/KafkaMessageSender.java, apiary-metastore-events/kafka-metastore-events/kafka-metastore-listener/src/main/java/com/expediagroup/apiary/extensions/events/metastore/kafka/messaging/KafkaProducerProperty.java, apiary-metastore-events/kafka-metastore-events/kafka-metastore-listener/src/test/java/com/expediagroup/apiary/extensions/events/metastore/kafka/messaging/KafkaProducerPropertyTest.java
Adding `compression.type` [Kafka property](https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html#compression-type) in `kafka-metastore-listener`.
=> Add Kafka compression type for Kafka Metastore Listener

CHANGELOG.md, apiary-metastore-events/kafka-metastore-events/kafka-metastore-listener/src/main/java/com/expediagroup/apiary/extensions/events/metastore/kafka/messaging/KafkaMessageSender.java, apiary-metastore-events/kafka-metastore-events/kafka-metastore-listener/src/main/java/com/expediagroup/apiary/extensions/events/metastore/kafka/messaging/KafkaProducerProperty.java, apiary-metastore-events/kafka-metastore-events/kafka-metastore-listener/src/test/java/com/expediagroup/apiary/extensions/events/metastore/kafka/messaging/KafkaProducerPropertyTest.java
Added `max.request.size` [Kafka property](https://kafka.apache.org/documentation/#producerconfigs_max.request.size) in `kafka-metastore-listener`.
=> Add max request size Kafka config in Metastore Event Listener

CHANGELOG.md, apiary-metastore-events/sns-metastore-events/apiary-receivers/apiary-receiver-sqs/pom.xml
Add sts dependency in apiary-receiver-sqs to avoid assume role issues in AWS
=> Add sts dependency to apiary-receiver-sqs

CHANGELOG.md, apiary-metastore-events/sns-metastore-events/apiary-receivers/apiary-receiver-sqs/pom.xml
Upgrade aws sdk version to avoid irsa issues
=> Fix: Update aws version in apiary receiver sqs

hive-event-listeners/apiary-gluesync-listener/README.md
=> fix:Update README.md

CHANGELOG.md, hive-event-listeners/apiary-gluesync-listener/src/main/java/com/expediagroup/apiary/extensions/gluesync/listener/service/HiveToGlueTransformer.java
Hive StorageDescriptor Field | File Format (Classification)
-- | --
InputFormat |  
↳ org.apache.hadoop.hive.ql.io.avro.AvroContainerInputFormat | avro
↳ org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat | parquet
↳ org.apache.hadoop.hive.ql.io.orc.OrcInputFormat | orc
For Iceberg 
https://iceberg.apache.org/docs/1.5.1/configuration/#write-properties
=> Add classification support for parquet, avro and orc table formats

CHANGELOG.md, hive-event-listeners/apiary-gluesync-listener/src/main/java/com/expediagroup/apiary/extensions/gluesync/listener/service/HiveToGlueTransformer.java
- Looks like SerDes are not required for all Hive tables, we found some JDBC tables without it and threw a NPE.
=> Fix Glue classification NPE when SerDes are not found
