ExpediaGroup/apiary-extensions

apiary-metastore-listener/README.md, apiary-metastore-listener/src/main/java/com/expedia/apiary/extensions/metastore/listener/ApiarySnsListener.java, apiary-metastore-listener/src/test/java/com/expedia/apiary/extensions/metastore/listener/ApiarySnsListenerTest.java
Unit tests for missing events and updating README with sample JSON response
=> Adding some unit tests for additional events

CHANGELOG.md, apiary-gluesync-listener/pom.xml, apiary-metastore-listener/pom.xml, apiary-metastore-metrics/pom.xml, apiary-ranger-metastore-plugin/pom.xml
=> Removed transitive dependency on org.apache.hbase hbase-client

apiary-metastore-metrics/pom.xml, pom.xml
=> Add managed dependency on mapreduce-client-core

CHANGELOG.md, apiary-metastore-auth/README.md, apiary-metastore-auth/pom.xml, apiary-metastore-auth/src/main/java/com/expedia/apiary/extensions/readonlyauth/listener/ApiaryReadOnlyAuthPreEventListener.java, apiary-metastore-auth/src/test/java/com/expedia/apiary/extensions/readonlyauth/listener/ApiaryReadOnlyAuthPreEventListenerTest.java, pom.xml
required for 
https://github.com/ExpediaInc/apiary-data-lake/issues/86
=> ReadOnly Auth Event Listener

CHANGELOG.md, apiary-metastore-listener/README.md, apiary-metastore-listener/pom.xml, apiary-metastore-listener/src/main/java/com/expedia/apiary/extensions/metastore/listener/ApiarySnsListener.java, apiary-metastore-listener/src/test/java/com/expedia/apiary/extensions/metastore/listener/ApiarySnsListenerTest.java
Adding table / partition location and table parameters to Apiary Events.
=> Add location & Table Params info to events

CHANGELOG.md, apiary-metastore-listener/README.md, apiary-metastore-listener/src/main/java/com/expedia/apiary/extensions/metastore/listener/ApiarySnsListener.java, apiary-metastore-listener/src/main/java/com/expedia/apiary/extensions/metastore/listener/MessageAttributeKey.java, apiary-metastore-listener/src/test/java/com/expedia/apiary/extensions/metastore/listener/ApiarySnsListenerTest.java
- Exposed eventType as MessageAttribute
=> Allow filtering of SNS messages on eventType

CHANGELOG.md, apiary-metastore-listener/src/main/java/com/expedia/apiary/extensions/metastore/listener/ApiarySnsListener.java, apiary-metastore-listener/src/main/java/com/expedia/apiary/extensions/metastore/listener/MessageAttributeDataType.java, apiary-metastore-listener/src/test/java/com/expedia/apiary/extensions/metastore/listener/ApiarySnsListenerTest.java
- Added DataType for the `eventType` MessageAttribute
=> Fixed message attributes filter

README.md
Added an overview for the repo and added a deployment section for apiary-extensions-terraform.
=> Updating readme files to reflect Apiary-extensions-terraform

CHANGELOG.md, apiary-metastore-events/apiary-metastore-listener/README.md, apiary-metastore-events/apiary-metastore-listener/src/main/java/com/expediagroup/apiary/extensions/events/metastore/listener/ApiarySnsListener.java, apiary-metastore-events/apiary-metastore-listener/src/main/java/com/expediagroup/apiary/extensions/events/metastore/listener/MessageAttributeKey.java, apiary-metastore-events/apiary-metastore-listener/src/test/java/com/expediagroup/apiary/extensions/events/metastore/listener/ApiarySnsListenerTest.java
Adding DB_NAME and TABLE_NAME to SNS message attributes for HMS events.
=> Adding db_name and table_name to HMS SNS message attributes

apiary-metastore-events/kafka-metastore-events/kafka-events-common/src/test/java/com.expediagroup.apiary.extensions.events.metastore/common/listener/AbstractMetaStoreEventListenerTest.java, apiary-metastore-events/kafka-metastore-events/kafka-events-common/src/test/java/com.expediagroup.apiary.extensions.events.metastore/common/listener/ListenerUtilsTest.java, apiary-metastore-events/kafka-metastore-events/kafka-events-common/src/test/java/com.expediagroup.apiary.extensions.events.metastore/common/listener/TestAppender.java, apiary-metastore-events/kafka-metastore-events/kafka-events-common/src/test/java/com.expediagroup.apiary.extensions.events.metastore/common/metrics/ExceptionMetrics.java, apiary-metastore-events/kafka-metastore-events/kafka-events-common/src/test/java/com.expediagroup.apiary.extensions.events.metastore/common/metrics/HiveMetricsHelperTest.java, apiary-metastore-events/kafka-metastore-events/pom.xml
Removing powermock from kafka tests
=> Remove powermock

apiary-metastore-events/kafka-metastore-events/kafka-metastore-listener/pom.xml
Using maven shade plugin to create uber jar for the listener
=> Using shade plugin to create uber jar

CHANGELOG.md, apiary-metastore-events/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-metastore-consumers/metastore-consumer-common/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-metastore-consumers/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-metastore-consumers/privileges-grantor/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-metastore-consumers/privileges-grantor/privileges-grantor-core/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-metastore-consumers/privileges-grantor/privileges-grantor-lambda/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-metastore-listener/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-receivers/apiary-receiver-common/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-receivers/apiary-receiver-sqs/pom.xml, apiary-metastore-events/sns-metastore-events/apiary-receivers/pom.xml, apiary-metastore-events/sns-metastore-events/pom.xml, apiary-metastore-metrics/pom.xml, hive-metastore-events/apiary-gluesync-listener/pom.xml, hive-metastore-events/apiary-metastore-auth/pom.xml, hive-metastore-events/apiary-ranger-metastore-plugin/pom.xml, hive-metastore-events/pom.xml, pom.xml
=> Prepare for release 5.0.0

.travis.yml, CHANGELOG.md, pom.xml
I made these changes due to some other things I'm testing and figured they're worth pushing upstream so here they are. BeeJU not mentioned in CHANGELOG since it's internal testing tool.
=> Upgrade BeeJU and parent versions

.github/workflows/main.yml, .travis.yml, README.md
* use action for coverage report instead of coveralls
* add badges to README
=> Add GH action

CHANGELOG.md, hive-hooks/src/main/java/com/expediagroup/apiary/extensions/hooks/pathconversion/converters/PathConverter.java, hive-hooks/src/test/java/com/expediagroup/apiary/extensions/hooks/pathconversion/converters/PathConverterTest.java
Added Partition->SD 'path' preoperty and table-'avro.schema.url' property.
=> Hive hook path parameter conversion

CHANGELOG.md, hive-event-listeners/apiary-gluesync-listener/src/main/java/com/expediagroup/apiary/extensions/gluesync/listener/ApiaryGluePreEventListener.java, hive-event-listeners/apiary-gluesync-listener/src/main/java/com/expediagroup/apiary/extensions/gluesync/listener/ApiaryGlueSync.java, hive-event-listeners/apiary-gluesync-listener/src/test/java/com/expediagroup/apiary/extensions/gluesync/listener/ApiaryGlueSyncTest.java
Adding GlueSync implementations for `onCreateDatabase` and `onDropDatabase` events.
=> Add support for creating+dropping Glue dbs

CHANGELOG.md, apiary-metastore-events/sns-metastore-events/apiary-metastore-consumers/privileges-grantor/privileges-grantor-lambda/src/assembly/aws-lambda-assembly.xml, apiary-metastore-events/sns-metastore-events/apiary-metastore-listener/pom.xml
=> Added sts library to fix assume role errors in AWS deployments

CHANGELOG.md
=> fixed changelog after failed release

.github/workflows/build.yml, CHANGELOG.md
=> Fix snapshot action

CHANGELOG.md, apiary-metastore-events/kafka-metastore-events/kafka-metastore-integration-tests/pom.xml, apiary-metastore-events/kafka-metastore-events/pom.xml
=> feat: kafka clients update

CHANGELOG.md, hive-event-listeners/apiary-gluesync-listener/pom.xml, hive-event-listeners/apiary-gluesync-listener/src/main/java/com/expediagroup/apiary/extensions/gluesync/listener/metrics/MetricConstants.java, hive-event-listeners/apiary-gluesync-listener/src/main/java/com/expediagroup/apiary/extensions/gluesync/listener/metrics/MetricService.java
=> Add micrometer for apiary-glue-event-listener

CHANGELOG.md, apiary-metastore-events/apiary-hive-events/src/main/java/com/expediagroup/apiary/extensions/events/metastore/io/jackson/JsonMetaStoreEventSerDe.java
Pass through cause of SerDe Exceptions
=> fix: Pass through cause in JsonMetaStoreEventSerDe
